# Generated by Django 5.0.6 on 2024-05-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcheckout',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
